version: "3.8"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4000:4000"

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "5000:5000"

  kong:
    image: kong:3.7
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - ./kong/kong.yml:/kong.yml
    ports:
      - "80:8000" # proxy
      - "8001:8001" # admin API
